"""
script to add columns the redseal rule usage/check tsv-files necessary for completing the semiannual FW rule review

You specify a directory containing the tsv files and a directory in which to place the altered files generated by
this script.  You can also specify a yaml file containing the columns to be added to the files.  This script will
add certain fields by default if no yaml file is specified on the command line.

options are:
  --source-dir
  --output-dir
  --column-config-file
"""

import yaml

import lib

args = lib.get_args()

file_list = lib.get_files()

f = open(args.column-config-file)
column_defs = yaml.